DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL NOT NULL,
    USER_ID VARCHAR(20) NOT NULL,
    USER_NM VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    USER_ROLE VARCHAR(50) NOT NULL,
    CRT_ID VARCHAR(20),
    CRT_DT TIMESTAMP,
    MDF_ID VARCHAR(20),
    MDF_DT TIMESTAMP,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID)
);